extends:
  - stylelint-config-css-modules
rules:
  indentation: 4
  max-nesting-depth: 2
  selector-class-pattern: null
  property-no-unknown:
    - true
    - ignoreProperties:
      - composes
      - compose-with
